### PR TITLE
Refactor lsq assembly

### PR DESCRIPTION
**Pull request by bernstei**
Refactor assembly of design matrix and RHS so that initial fit and addition of blocks when configs are added uses the same low level code.

At the same time, deal with missing data, drop F > Fmax at construction time instead of by multiplying rows by 0, and drop 3 redundant elements on virial.

Also add some code to annotate saved configs with what iter and predicted force error led to them being selected.

### CODE REVIEW

**Comment by bernstei** [comment]
Definitely don't merge, BTW.  I'm still refactoring.

**Comment by bernstei** [comment]
I think the form it's in now is basically what I want, although it's not fully tested yet.

**Comment by bernstei** [comment]
I think it's running correctly now.

**Comment by casv2** [comment]
Thanks, this looks good!

**Pull request merged**
